# Generated by Django 3.1.3 on 2020-11-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, choices=[('sensors', 'Sensors'), ('actuators', 'Actuators')], db_index=True, max_length=40, null=True),
        ),
    ]
