# Generated by Django 3.1.3 on 2020-11-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201120_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_discount_from_store',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='start_discount_from_quantity',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
